# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'AncientArchitecture' do

 # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
 # use_frameworks!

 # Pods for AncientArchitecture

pod 'AFNetworking', '~> 3.0'

pod 'SDWebImage', '~> 4.0'

pod 'MJExtension'
pod 'Bugly'
pod 'WechatOpenSDK'

pod 'MBProgressHUD'
pod 'TZImagePickerController'


pod 'AlivcLivePusherWithPlayer'
pod 'AliyunPlayer_iOS/AliyunPlayerSDK'


pod 'MJRefresh'

pod 'PGDatePicker'

pod 'SDCycleScrollView','~> 1.64'

pod 'WMPageController','~>2.3.0'

pod 'VTMagic'
end
