# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'AncientArchitecture' do
    
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for AncientArchitecture
    
    pod 'AFNetworking', '3.0'
    
    pod 'SDWebImage'
    pod 'YYWebImage'
  
  
    pod 'MJExtension'

    pod 'WechatOpenSDK'
    
    pod 'MBProgressHUD'
    pod 'TZImagePickerController'
    
    
    pod 'AlivcLivePusher'
    pod 'AliyunPlayer_iOS', '3.4.3'

    pod 'MJRefresh'
    
    pod 'PGDatePicker'
    
    pod 'SDCycleScrollView'
    
    pod 'WMPageController'
    
    pod 'VTMagic'
    
#    pod 'PLPlayerKit'

#    pod 'Pgyer'
#    pod 'PgyUpdate'

    pod 'DZNEmptyDataSet'
    pod 'Bugly'
end
